"""Mobile dashboard UI function definitions (Phase 176C)."""

from __future__ import annotations

from backend.reports_center.constants import CATEGORIES
from dashboard.ui_function.models import CSSUIFunctionDefinition, defn

_MOBILE_NAV = (
    ("dashboard", "/dashboard", "Dashboard", "session"),
    ("reports", "/reports", "Reports", "reports_view"),
    ("positions", "/positions", "Positions", "session"),
    ("history", "/history", "History", "session"),
    ("risk", "/risk", "Risk", "session"),
    ("governance", "/governance", "Governance", "session"),
    ("opportunities", "/opportunities", "Opportunities", "session"),
    ("market", "/market", "Market", "session"),
    ("broker", "/broker", "Broker", "session"),
    ("session-command-centre", "/session-command-centre", "Command Centre", "session"),
    ("trade-status", "/trade-status", "Trade Status", "session"),
    ("trade-summary", "/trade-summary", "Trade Summary", "session"),
    ("live-micro-pilot", "/live-micro-pilot", "Micro-Pilot", "session"),
    ("live-readiness-certification", "/live-readiness-certification", "Live Cert", "session"),
    ("alerts", "/alerts", "Alert Centre", "session"),
    ("margin", "/margin", "Margin", "session"),
    ("audit", "/audit", "Audit", "view_audit_logs"),
    ("trade", "/trade", "Trade", "submit_trade"),
    ("controls", "/controls", "Controls", "manage_system"),
    ("users", "/users", "Users", "SUPER_USER"),
)

MOBILE_CONTROLS: list[CSSUIFunctionDefinition] = []

for key, route, label, perm in _MOBILE_NAV:
    MOBILE_CONTROLS.append(
        defn(
            control_id=f"mobile.nav.{key}",
            page_id=f"mobile_{key.replace('-', '_')}",
            section="navigation",
            label=label,
            control_type="nav",
            mobile_route=route,
            required_permission=perm,
            expected_action="navigate_with_active_aria_current",
            expected_api=f"GET {route}",
            expected_success_state="html_200_active_marked",
            evidence_source="dashboard/mobile/mobile_app.py:_top_nav",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_nav_active",
            desktop_mobile="MOBILE_ONLY",
        )
    )

MOBILE_CONTROLS.append(
    defn(
        control_id="mobile.nav.logout",
        page_id="mobile_shell",
        section="navigation",
        label="Logout",
        control_type="form",
        mobile_route="/logout",
        expected_action="clear_session",
        expected_api="POST /logout",
        implementation_status="FUNCTIONAL",
        test_id="test_mobile_logout_route",
        desktop_mobile="MOBILE_ONLY",
    )
)

for key in CATEGORIES:
    MOBILE_CONTROLS.append(
        defn(
            control_id=f"mobile.reports.category.{key}",
            page_id="mobile_reports",
            section="categories",
            label=f"Reports category {key}",
            control_type="disclosure",
            mobile_route=f"/reports?category={key}",
            required_permission="reports_view",
            expected_action="filter_and_open_disclosure",
            expected_service="ReportsCenterService / ui_contract",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_reports_categories",
            desktop_mobile="MOBILE_ONLY",
        )
    )

MOBILE_CONTROLS.extend(
    [
        defn(
            control_id="mobile.reports.create",
            page_id="mobile_reports",
            section="create",
            label="Create Report",
            control_type="form",
            mobile_route="/reports/create",
            required_permission="reports_generate",
            expected_action="POST_generate",
            expected_service="ReportsCenterService.generate",
            expected_api="POST /reports/generate",
            expected_success_state="archived_report_or_blockers",
            expected_failure_state="DENIED_or_error_banner",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_reports_generate",
            desktop_mobile="MOBILE_ONLY",
            safety_classification="ADVISORY_REPORTS",
        ),
        defn(
            control_id="mobile.reports.library",
            page_id="mobile_reports",
            section="library",
            label="Report Library",
            control_type="filter",
            mobile_route="/reports/library",
            required_permission="reports_view",
            expected_action="filter_library",
            expected_service="ReportsCenterService.list_library",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_reports_library_latest",
            desktop_mobile="MOBILE_ONLY",
        ),
        defn(
            control_id="mobile.reports.library.latest",
            page_id="mobile_reports",
            section="library",
            label="Latest Reports",
            control_type="link",
            mobile_route="/reports/library?view=latest",
            required_permission="reports_view",
            expected_action="show_recent_archived",
            expected_service="ReportsCenterService.list_library",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_reports_library_latest",
            desktop_mobile="MOBILE_ONLY",
            notes="Phase 176C: view=latest applies limit/sort of recent archive.",
        ),
        defn(
            control_id="mobile.reports.print",
            page_id="mobile_reports",
            section="detail",
            label="Print preview",
            control_type="link",
            mobile_route="/reports/detail/{id}",
            required_permission="reports_print_*",
            expected_api="GET /api/v1/reports/{id}/print",
            expected_service="ReportsCenterService.printable_html",
            expected_success_state="html_preview",
            expected_failure_state="DENIED_or_NOT_FOUND",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_reports_print_mounted",
            desktop_mobile="MOBILE_ONLY",
            notes="Phase 176C: reports center router mounted on mobile_app.",
        ),
        defn(
            control_id="mobile.reports.pdf",
            page_id="mobile_reports",
            section="detail",
            label="PDF info",
            control_type="link",
            mobile_route="/reports/detail/{id}",
            expected_api="GET /api/v1/reports/{id}/pdf",
            expected_service="ReportsCenterService.pdf_info",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_reports_print_mounted",
            desktop_mobile="MOBILE_ONLY",
        ),
        defn(
            control_id="mobile.alerts.filter",
            page_id="mobile_alerts",
            section="filters",
            label="Alert severity filters",
            control_type="filter",
            mobile_route="/alerts",
            expected_action="client_dom_filter",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_alerts_filters_present",
            desktop_mobile="MOBILE_ONLY",
            limitation="Client-side filterAlerts; no backend mutation.",
        ),
        defn(
            control_id="mobile.controls.save",
            page_id="mobile_controls",
            section="admin",
            label="Save Controls",
            control_type="form",
            mobile_route="/controls",
            required_permission="manage_system",
            expected_api="POST /controls",
            expected_service="_update_mobile_controls",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_controls_rbac",
            desktop_mobile="MOBILE_ONLY",
            safety_classification="GOVERNED_CONTROLS",
        ),
        defn(
            control_id="mobile.users.create",
            page_id="mobile_users",
            section="admin",
            label="Create User",
            control_type="form",
            mobile_route="/users",
            required_role="SUPER_USER",
            expected_api="POST /users",
            expected_service="create_user",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_users_rbac",
            desktop_mobile="MOBILE_ONLY",
        ),
        defn(
            control_id="mobile.trade.submit",
            page_id="mobile_trade",
            section="trade",
            label="Submit Ticket",
            control_type="form",
            mobile_route="/trade",
            required_permission="submit_trade",
            expected_api="POST /trade",
            expected_service="execute_mobile_trade_ticket",
            expected_success_state="ticket_result_or_gate_block",
            expected_failure_state="DENIED_or_gate_fail_closed",
            implementation_status="FUNCTIONAL_WITH_LIMITATIONS",
            test_id="test_mobile_trade_form_present",
            desktop_mobile="MOBILE_ONLY",
            safety_classification="LIVE_BLOCKED_DEFAULT",
            limitation="Live trading remains blocked unless explicitly armed under governance; advisory/paper path only by default.",
        ),
        defn(
            control_id="mobile.margin.refresh",
            page_id="mobile_margin",
            section="refresh",
            label="Refresh Margin",
            control_type="refresh",
            mobile_route="/margin",
            expected_api="GET /api/margin-snapshot",
            implementation_status="FUNCTIONAL",
            test_id="test_mobile_margin_api",
            desktop_mobile="MOBILE_ONLY",
        ),
        defn(
            control_id="mobile.micro_pilot.arm_apis",
            page_id="mobile_live_micro_pilot",
            section="admin",
            label="Micro-pilot arm/configure APIs",
            control_type="api_action",
            mobile_route="/live-micro-pilot",
            expected_api="POST /api/live-micro-pilot/*",
            implementation_status="DISABLED",
            availability_status="NO_VISIBLE_CONTROL",
            test_id="test_mobile_micropilot_display_only",
            desktop_mobile="MOBILE_ONLY",
            limitation="APIs exist but page is display-only; no visible arm/configure controls (honest DISABLED).",
            safety_classification="FAIL_CLOSED_NO_UI",
        ),
    ]
)
