"""
Event Registry for CSS Enterprise Event Bus

This module houses all centralized constants for event types, categories, and severities.
Hardcoded event names should be avoided throughout CSS in favor of these constants.
"""

# --- Event Categories ---
CATEGORY_ORDER = "ORDER"
CATEGORY_SYSTEM = "SYSTEM"
CATEGORY_RISK = "RISK"
CATEGORY_CAPITAL = "CAPITAL"
CATEGORY_GOVERNANCE = "GOVERNANCE"
CATEGORY_NOTIFICATION = "NOTIFICATION"
CATEGORY_AUDIT = "AUDIT"
CATEGORY_METRICS = "METRICS"

# --- Event Severities ---
SEVERITY_DEBUG = "DEBUG"
SEVERITY_INFO = "INFO"
SEVERITY_WARNING = "WARNING"
SEVERITY_ERROR = "ERROR"
SEVERITY_CRITICAL = "CRITICAL"

# --- Event Types ---

# Order Events
ORDER_CREATED = "ORDER_CREATED"
ORDER_SUBMITTED = "ORDER_SUBMITTED"
ORDER_FILLED = "ORDER_FILLED"
ORDER_CANCELLED = "ORDER_CANCELLED"
ORDER_REJECTED = "ORDER_REJECTED"

# Risk Subsystem Events
RISK_LIMIT_EXCEEDED = "RISK_LIMIT_EXCEEDED"
RISK_CHECK_PASSED = "RISK_CHECK_PASSED"
RISK_CHECK_FAILED = "RISK_CHECK_FAILED"

# System Control / Supervisor Events
SYSTEM_STARTUP = "SYSTEM_STARTUP"
SYSTEM_SHUTDOWN = "SYSTEM_SHUTDOWN"
SYSTEM_ERROR = "SYSTEM_ERROR"
SYSTEM_HEARTBEAT = "SYSTEM_HEARTBEAT"

# Capital Subsystem Events
CAPITAL_ALLOCATED = "CAPITAL_ALLOCATED"
CAPITAL_LIMIT_UPDATED = "CAPITAL_LIMIT_UPDATED"

# Governance & Certification Events
GOVERNANCE_CERTIFICATION_PASSED = "GOVERNANCE_CERTIFICATION_PASSED"
GOVERNANCE_CERTIFICATION_FAILED = "GOVERNANCE_CERTIFICATION_FAILED"

# Notification Dispatcher Events
NOTIFICATION_SENT = "NOTIFICATION_SENT"
NOTIFICATION_FAILED = "NOTIFICATION_FAILED"

# Audit Trail Events
AUDIT_LOGGED = "AUDIT_LOGGED"
