"""Phase 191 — seed registry from Phase 187–190 declared certifications."""

from __future__ import annotations

from backend.app.brokers.multi_broker_readiness.audit_matrix import get_capability_profile
from backend.app.governance.enterprise_certification_registry.hashing import RegistryHash
from backend.app.governance.enterprise_certification_registry.models import (
    SCHEMA_VERSION,
    CertificationRegistryEntry,
    RegistryEntityType,
)
from backend.app.governance.enterprise_certification_registry.repository import RegistryRepository


def _entry(**kwargs: object) -> CertificationRegistryEntry:
    entry = CertificationRegistryEntry(**kwargs)  # type: ignore[arg-type]
    # Fill evidence_hash if empty using deterministic entry hash of declared fields.
    if not entry.evidence_hash:
        digest = RegistryHash.hash_entry(entry)
        data = entry.as_dict()
        data["evidence_hash"] = digest
        # Rebuild with hash (still immutable after construction).
        return CertificationRegistryEntry(**{**data, "blocker_list": tuple(data["blocker_list"]), "phase_refs": tuple(data["phase_refs"])})
    return entry


def build_seed_entries() -> tuple[CertificationRegistryEntry, ...]:
    oanda_caps = get_capability_profile("OANDA").as_dict()
    coinbase_caps = get_capability_profile("COINBASE").as_dict()
    ibkr_caps = get_capability_profile("IBKR").as_dict()

    entries = [
        # Phase registrations
        _entry(
            registry_id="phase:192",
            entity_type=RegistryEntityType.PHASE.value,
            entity_name="PHASE_192_LDT_REFRESH_AND_RC004",
            provider_name="PHASE_192",
            provider_version="192.1",
            schema_version="192.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="READY",
            paper_status="N/A",
            read_only_status="N/A",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T12:00:00Z",
            next_validation="FOUNDER_REVIEW",
            phase_refs=("192",),
            blocker_list=("LIVE_TRADING_NOT_AUTHORIZED",),
        ),
        _entry(
            registry_id="phase:187A",
            entity_type=RegistryEntityType.PHASE.value,
            entity_name="PHASE_187A_OANDA_READONLY_CERTIFICATION_FRAMEWORK",
            provider_name="OANDA_ONLINE_READONLY_CERTIFICATION_FRAMEWORK",
            provider_version="187A.2",
            schema_version="187A.2",
            certification_status="FRAMEWORK_READY",
            operational_readiness="READY",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("187A",),
            blocker_list=("online_contact_requires_credentials",),
        ),
        _entry(
            registry_id="phase:188",
            entity_type=RegistryEntityType.PHASE.value,
            entity_name="PHASE_188_CONTROLLED_OANDA_READONLY_CERTIFICATION",
            provider_name="OANDA_CONTROLLED_READONLY_CERTIFIED_PROVIDER",
            provider_version="188.1",
            schema_version="188.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="PARTIAL",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("188", "187A"),
            blocker_list=("controlled_online_requires_credentials",),
        ),
        _entry(
            registry_id="phase:189",
            entity_type=RegistryEntityType.PHASE.value,
            entity_name="PHASE_189_MULTI_BROKER_OPERATIONAL_READINESS",
            provider_name="MULTI_BROKER_OPERATIONAL_READINESS_FRAMEWORK",
            provider_version="189.1",
            schema_version="189.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="PARTIAL",
            paper_status="ACKNOWLEDGED",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("189",),
            blocker_list=("RC004_live_unlock_absent", "IBKR_blocked", "BINANCE_not_started"),
        ),
        _entry(
            registry_id="phase:190",
            entity_type=RegistryEntityType.PHASE.value,
            entity_name="PHASE_190_RC_LIVE_ENTERPRISE_REVIEW",
            provider_name="RC_LIVE_ENTERPRISE_REVIEW",
            provider_version="190.1",
            schema_version="190.1",
            certification_status="PAPER_ONLY",
            operational_readiness="PARTIAL",
            paper_status="ACKNOWLEDGED",
            read_only_status="PARTIAL",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("190",),
            blocker_list=(
                "freeze_sha_not_designated",
                "RC004_artifact_missing",
                "pilot_no_go",
                "production_no_go",
            ),
        ),
        _entry(
            registry_id="phase:191",
            entity_type=RegistryEntityType.PHASE.value,
            entity_name="PHASE_191_ENTERPRISE_CERTIFICATION_REGISTRY",
            provider_name="ENTERPRISE_CERTIFICATION_REGISTRY",
            provider_version="191.1",
            schema_version=SCHEMA_VERSION,
            certification_status="FRAMEWORK_READY",
            operational_readiness="READY",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("191", "190", "189", "188", "187A"),
            blocker_list=(),
        ),
        # Brokers
        _entry(
            registry_id="broker:OANDA",
            entity_type=RegistryEntityType.BROKER.value,
            entity_name="OANDA",
            broker_type="OANDA",
            asset_class="FX",
            provider_name="OandaLiveReadOnlyAdapter",
            provider_version="188.1",
            schema_version="189.1",
            capability_profile=oanda_caps,
            certification_status="PARTIAL",
            operational_readiness="PARTIAL",
            paper_status="ACKNOWLEDGED",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            authorization_ttl_status="N/A",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="CONTROLLED_ONLINE_RO",
            phase_refs=("187A", "188", "189", "190"),
            blocker_list=("online_credentials_required", "LIVE_not_certified"),
        ),
        _entry(
            registry_id="broker:COINBASE",
            entity_type=RegistryEntityType.BROKER.value,
            entity_name="COINBASE",
            broker_type="COINBASE",
            asset_class="CRYPTO",
            provider_name="CoinbaseLiveReadOnly",
            provider_version="HISTORICAL",
            schema_version="189.1",
            capability_profile=coinbase_caps,
            certification_status="PARTIAL",
            operational_readiness="PARTIAL",
            paper_status="ACKNOWLEDGED",
            read_only_status="PARTIAL",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="UNIFY_UNDER_189",
            phase_refs=("189", "190"),
            blocker_list=("unify_under_phase189_state_machine",),
        ),
        _entry(
            registry_id="broker:IBKR",
            entity_type=RegistryEntityType.BROKER.value,
            entity_name="IBKR",
            broker_type="IBKR",
            asset_class="MULTI",
            provider_name="IBKR_PLACEHOLDER",
            provider_version="NONE",
            schema_version="189.1",
            capability_profile=ibkr_caps,
            certification_status="BLOCKED",
            operational_readiness="BLOCKED",
            paper_status="BLOCKED",
            read_only_status="BLOCKED",
            live_status="NOT_AUTHORIZED",
            certification_generation=0,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="KEEP_QUARANTINED",
            suspension_status="SUSPENDED",
            phase_refs=("189", "190"),
            blocker_list=("roadmap_excluded_177C",),
        ),
        # Providers
        _entry(
            registry_id="provider:oanda_readonly_certification",
            entity_type=RegistryEntityType.PROVIDER.value,
            entity_name="oanda_readonly_certification",
            broker_type="OANDA",
            provider_name="OANDA_ONLINE_READONLY_CERTIFICATION_FRAMEWORK",
            provider_version="187A.2",
            schema_version="187A.2",
            certification_status="FRAMEWORK_READY",
            operational_readiness="READY",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("187A",),
            blocker_list=(),
        ),
        _entry(
            registry_id="provider:oanda_controlled_readonly",
            entity_type=RegistryEntityType.PROVIDER.value,
            entity_name="oanda_controlled_readonly",
            broker_type="OANDA",
            provider_name="OANDA_CONTROLLED_READONLY_CERTIFIED_PROVIDER",
            provider_version="188.1",
            schema_version="188.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="PARTIAL",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="CONTROLLED_ONLINE_RO",
            phase_refs=("188",),
            blocker_list=("credentials_required_for_online",),
        ),
        _entry(
            registry_id="provider:multi_broker_readiness",
            entity_type=RegistryEntityType.PROVIDER.value,
            entity_name="multi_broker_readiness",
            provider_name="MULTI_BROKER_OPERATIONAL_READINESS_FRAMEWORK",
            provider_version="189.1",
            schema_version="189.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="PARTIAL",
            paper_status="ACKNOWLEDGED",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            authorization_ttl_status="N/A",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("189",),
            blocker_list=(),
        ),
        # Assets / market data / FX / microstructure
        _entry(
            registry_id="asset:FX",
            entity_type=RegistryEntityType.ASSET.value,
            entity_name="FX",
            broker_type="OANDA",
            asset_class="FX",
            provider_name="PHASE_185A_186A",
            provider_version="186A.1",
            schema_version="185A.1",
            certification_status="PARTIAL",
            operational_readiness="PARTIAL",
            paper_status="ACKNOWLEDGED",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ONLINE_RO",
            phase_refs=("185A", "186A", "189", "190"),
            blocker_list=("online_fx_cert_pending",),
        ),
        _entry(
            registry_id="asset:CRYPTO",
            entity_type=RegistryEntityType.ASSET.value,
            entity_name="CRYPTO",
            broker_type="COINBASE",
            asset_class="CRYPTO",
            provider_name="COINBASE_HISTORICAL_RO",
            provider_version="HISTORICAL",
            schema_version="189.1",
            certification_status="PARTIAL",
            operational_readiness="PARTIAL",
            paper_status="N/A",
            read_only_status="PARTIAL",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="UNIFY_UNDER_189",
            phase_refs=("189", "190"),
            blocker_list=("binance_not_started",),
        ),
        _entry(
            registry_id="market_data:offline_providers",
            entity_type=RegistryEntityType.MARKET_DATA.value,
            entity_name="PHASE_186A_OFFLINE_PROVIDERS",
            provider_name="OFFLINE_CERTIFICATION_PROVIDERS",
            provider_version="186A.1",
            schema_version="185A.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="READY",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ON_DEMAND",
            phase_refs=("185A", "186A"),
            blocker_list=(),
        ),
        _entry(
            registry_id="fx:contracts",
            entity_type=RegistryEntityType.FX.value,
            entity_name="PHASE_185A_FX_CONTRACTS",
            provider_name="FX_CONVERSION_CONTRACTS",
            provider_version="185A.1",
            schema_version="185A.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="PARTIAL",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="ONLINE_FX_CERT",
            phase_refs=("185A", "186A", "190"),
            blocker_list=("online_fx_conversion_uncertified",),
        ),
        _entry(
            registry_id="microstructure:offline",
            entity_type=RegistryEntityType.MICROSTRUCTURE.value,
            entity_name="PHASE_186A_MICROSTRUCTURE",
            provider_name="OFFLINE_CERTIFICATION_MICROSTRUCTURE",
            provider_version="186A.1",
            schema_version="185A.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="PARTIAL",
            paper_status="N/A",
            read_only_status="FRAMEWORK_READY",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T00:00:00Z",
            next_validation="LIVE_MICROSTRUCTURE_CERT",
            phase_refs=("186A", "190"),
            blocker_list=("live_microstructure_default_unavailable",),
        ),
        # Governance
        _entry(
            registry_id="governance:RC004",
            entity_type=RegistryEntityType.GOVERNANCE.value,
            entity_name="RC004",
            provider_name="RC004_OPERATIONAL_POSTURE",
            provider_version="192.1",
            schema_version="192.1",
            certification_status="PAPER_ONLY",
            operational_readiness="READY",
            paper_status="ACKNOWLEDGED",
            read_only_status="N/A",
            live_status="NOT_AUTHORIZED",
            certification_generation=2,
            last_validation="2026-08-01T12:00:00Z",
            next_validation="FOUNDER_LIVE_PHASE_IF_AUTHORIZED",
            phase_refs=("189", "190", "191", "192"),
            blocker_list=(
                "BLK-RC004-LIVE-UNLOCK",
                "LIVE_TRADING_NOT_AUTHORIZED",
            ),
        ),
        _entry(
            registry_id="governance:LDT",
            entity_type=RegistryEntityType.GOVERNANCE.value,
            entity_name="LDT_PROGRAMME",
            provider_name="LDT_001_002_192",
            provider_version="192.1",
            schema_version="192.1",
            certification_status="BLOCKED",
            operational_readiness="BLOCKED",
            paper_status="N/A",
            read_only_status="N/A",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T12:00:00Z",
            next_validation="AFTER_BLOCKER_CLEARANCE_AND_FREEZE",
            phase_refs=("LDT-001", "LDT-002", "192"),
            blocker_list=(
                "BLK-FREEZE-SHA",
                "BLK-FX-CONVERSION",
                "BLK-OANDA-LIVE",
                "BLK-AUTH-TTL",
                "BLK-RC004-LIVE-UNLOCK",
                "BLK-FOUNDER-LIVE-GO",
            ),
        ),
        _entry(
            registry_id="governance:PHASE192",
            entity_type=RegistryEntityType.GOVERNANCE.value,
            entity_name="PHASE_192_LDT_REFRESH_AND_RC004",
            provider_name="PHASE_192",
            provider_version="192.1",
            schema_version="192.1",
            certification_status="FRAMEWORK_READY",
            operational_readiness="READY",
            paper_status="N/A",
            read_only_status="N/A",
            live_status="NOT_AUTHORIZED",
            certification_generation=1,
            last_validation="2026-08-01T12:00:00Z",
            next_validation="FOUNDER_REVIEW",
            phase_refs=("192",),
            blocker_list=("LIVE_TRADING_NOT_AUTHORIZED",),
        ),
    ]
    return tuple(entries)


def seed_phase_registry(repository: RegistryRepository | None = None) -> RegistryRepository:
    repo = repository or RegistryRepository()
    repo.extend(build_seed_entries())
    return repo
