from __future__ import annotations

REGIME_TRENDING_UP = "TRENDING_UP"
REGIME_TRENDING_DOWN = "TRENDING_DOWN"
REGIME_RANGING = "RANGING"
REGIME_HIGH_VOLATILITY = "HIGH_VOLATILITY"
REGIME_LOW_VOLATILITY = "LOW_VOLATILITY"
REGIME_CORRELATION_STRESS = "CORRELATION_STRESS"
REGIME_UNKNOWN = "UNKNOWN"

CANONICAL_REGIMES = {
    REGIME_TRENDING_UP,
    REGIME_TRENDING_DOWN,
    REGIME_RANGING,
    REGIME_HIGH_VOLATILITY,
    REGIME_LOW_VOLATILITY,
    REGIME_CORRELATION_STRESS,
    REGIME_UNKNOWN,
}

LEGACY_REGIME_ALIASES = {
    "TRENDING": REGIME_TRENDING_UP,
}

RECOMMENDATION_PAUSE_NEW_TRADES = "PAUSE_NEW_TRADES"
RECOMMENDATION_REDUCE_RISK = "REDUCE_RISK"
RECOMMENDATION_MAINTAIN = "MAINTAIN"
RECOMMENDATION_REBALANCE = "REBALANCE"
RECOMMENDATION_INCREASE_RISK = "INCREASE_RISK"

RECOMMENDATION_ORDER = {
    RECOMMENDATION_PAUSE_NEW_TRADES: 0,
    RECOMMENDATION_REDUCE_RISK: 1,
    RECOMMENDATION_MAINTAIN: 2,
    RECOMMENDATION_REBALANCE: 2,
    RECOMMENDATION_INCREASE_RISK: 3,
}

STATUS_DATA_UNAVAILABLE = "DATA UNAVAILABLE"
ADVISORY_ONLY = True
EXECUTION_ALLOWED = False
