"""Deterministic customer commercial statements from durable records.

A statement is derived only from collection records and their append-only
lifecycle history, so it can be regenerated byte-for-byte at any time; the
statement identifier is a hash of its content and no wall-clock time is used.

Money is presented as ``paid`` only when the collection carries full
settlement AND reconciliation evidence (``may_be_marked_paid``). Everything
else is reported in its own category; the statement deliberately makes no
"balance due" claim, which would depend on approved business rules for
failed collections and adjustments.
"""
import hashlib
import json
from dataclasses import asdict, dataclass
from decimal import Decimal
from typing import Dict, Iterable, List, Optional, Set, Tuple

from engine.commercial.collection_history import CollectionEvent, CollectionHistoryRepository
from engine.domain.collections import CollectionStatus, CollectionTransaction

_ADJUSTED = {CollectionStatus.REFUNDED, CollectionStatus.REVERSED, CollectionStatus.CHARGEBACK}
_IN_PROGRESS = {CollectionStatus.INITIATED, CollectionStatus.AUTHORIZED}
TOTAL_KEYS = (
    "total_obligations", "paid", "settled_unreconciled", "reversed_refunded_chargeback",
    "in_progress", "failed", "obligation",
)


@dataclass(frozen=True)
class StatementLine:
    collection_id: str
    obligation_id: str
    account_id: str
    amount: Decimal
    currency: str
    status: str
    state: str
    paid: bool
    has_open_exception: bool
    settlement_reference: Optional[str]
    ledger_txn_id: Optional[str]
    reconciliation_reference: Optional[str]
    events: Tuple[CollectionEvent, ...]


@dataclass(frozen=True)
class CommercialStatement:
    statement_id: str
    customer_id: str
    lines: Tuple[StatementLine, ...]
    totals: Dict[str, Dict[str, Decimal]]


def classify(collection: CollectionTransaction) -> str:
    if collection.status == CollectionStatus.SETTLED:
        return "reconciled" if collection.may_be_marked_paid else "settled"
    return collection.status.value.lower()


def build_statement(
    customer_id: str,
    collections: Iterable[CollectionTransaction],
    *,
    history: CollectionHistoryRepository,
    open_exception_collection_ids: Optional[Set[str]] = None,
) -> CommercialStatement:
    if not customer_id:
        raise ValueError("customer id required")
    open_ids = set(open_exception_collection_ids or ())
    items: List[CollectionTransaction] = list(collections)
    strangers = sorted({c.customer_id for c in items if c.customer_id != customer_id})
    if strangers:
        raise ValueError(f"statement for {customer_id} received records belonging to {', '.join(strangers)}")

    lines = []
    totals: Dict[str, Dict[str, Decimal]] = {}
    for c in sorted(items, key=lambda x: (x.obligation_id, x.collection_id)):
        state = classify(c)
        lines.append(StatementLine(
            collection_id=c.collection_id, obligation_id=c.obligation_id, account_id=c.account_id,
            amount=c.amount, currency=c.currency, status=c.status.value, state=state,
            paid=c.may_be_marked_paid, has_open_exception=c.collection_id in open_ids,
            settlement_reference=c.settlement_reference, ledger_txn_id=c.ledger_txn_id,
            reconciliation_reference=c.meta.get("reconciliation_reference"),
            events=tuple(history.history(c.collection_id)),
        ))
        bucket = totals.setdefault(c.currency, {k: Decimal("0.00") for k in TOTAL_KEYS})
        bucket["total_obligations"] += c.amount
        if c.may_be_marked_paid:
            bucket["paid"] += c.amount
        elif c.status == CollectionStatus.SETTLED:
            bucket["settled_unreconciled"] += c.amount
        elif c.status in _ADJUSTED:
            bucket["reversed_refunded_chargeback"] += c.amount
        elif c.status in _IN_PROGRESS:
            bucket["in_progress"] += c.amount
        elif c.status == CollectionStatus.FAILED:
            bucket["failed"] += c.amount
        else:
            bucket["obligation"] += c.amount

    canonical = json.dumps(
        {"customer_id": customer_id, "lines": [asdict(line) for line in lines], "totals": totals},
        sort_keys=True, default=str, separators=(",", ":"),
    )
    statement_id = "CSS-STM-" + hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:32]
    return CommercialStatement(statement_id=statement_id, customer_id=customer_id, lines=tuple(lines), totals=totals)
