"""Phase 185A — shared market-data status tokens (fail-closed)."""

from __future__ import annotations

# Authoritative status strings. UNKNOWN and NOT_AVAILABLE never grant execution.
STATUS_NOT_AVAILABLE = "NOT_AVAILABLE"
STATUS_UNKNOWN = "UNKNOWN"
STATUS_AVAILABLE = "AVAILABLE"

QUALITY_UNKNOWN = "UNKNOWN"
QUALITY_UNVERIFIED = "UNVERIFIED"
QUALITY_CERTIFIED = "CERTIFIED"

FRESHNESS_UNKNOWN = "UNKNOWN"
FRESHNESS_NOT_AVAILABLE = "NOT_AVAILABLE"

PROVIDER_NONE = "NONE"
PROVIDER_VERSION_NONE = "0"

# Phase 185A-R1 — unavailable provider identity (not a live implementation).
UNAVAILABLE_PROVIDER_NAME = "UNAVAILABLE_PROVIDER"
UNAVAILABLE_PROVIDER_VERSION = "185A.1"

FRAMEWORK_VERSION = "185A.1"

SCHEMA_ID_LIVE_MARKET_SNAPSHOT = "LIVE_MARKET_SNAPSHOT"
SCHEMA_ID_FX_CONVERSION = "FX_CONVERSION"
SCHEMA_VERSION_185A = "185A.1"

# RC-LIVE-CONSOL-001 recovery posture — contracts/providers never grant live I/O or execution.
LIVE_NETWORK_INGESTION = False
EXECUTION_ALLOWED = False
ADVISORY_ONLY = True
