CREATE TABLE IF NOT EXISTS commercial_final_fee_selections (
    fee_selection_id TEXT NOT NULL PRIMARY KEY,
    access_terms_id TEXT NOT NULL,
    terms_id TEXT NOT NULL,
    policy_id TEXT NOT NULL,
    billing_currency TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    platform_access_fee_amount TEXT NOT NULL,
    performance_fee_source_currency TEXT NOT NULL,
    performance_fee_source_amount TEXT NOT NULL,
    performance_fee_billing_currency_amount TEXT NOT NULL,
    selected_fee_amount TEXT NOT NULL,
    selected_fee_basis TEXT NOT NULL,
    selected_at TEXT NOT NULL,
    evidence_refs_json TEXT NOT NULL,
    fx_conversion_id TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    CHECK (length(trim(fee_selection_id)) > 0),
    CHECK (evidence_refs_json != '[]'),
    CHECK (billing_currency = 'USD'),
    CHECK (selected_fee_basis IN ('PLATFORM_ACCESS', 'PERFORMANCE_COMPENSATION')),
    FOREIGN KEY (access_terms_id) REFERENCES platform_access_fee_terms(access_terms_id) ON DELETE RESTRICT,
    FOREIGN KEY (terms_id) REFERENCES performance_compensation_terms(terms_id) ON DELETE RESTRICT,
    FOREIGN KEY (policy_id, period_start, period_end) REFERENCES crystallization_assessments(policy_id, period_start, period_end) ON DELETE RESTRICT,
    FOREIGN KEY (fx_conversion_id) REFERENCES commercial_fx_conversion_evidence(fx_conversion_id) ON DELETE RESTRICT
);
