from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from backend.config.order_limit_config import DEFAULT_ORDER_LIMIT_CONFIG


def mission_control_mock_dashboard_payload() -> dict[str, Any]:
    """Explicitly labeled deterministic demo data for MC-001 rendering tests."""

    now = datetime.now(timezone.utc).isoformat()
    return {
        "session_id": "MC001-DEMO-SESSION",
        "resolved_mode": "paper",
        "session": {
            "user_id": "demo_user",
            "role": "TRADER",
            "unit": "DEMO",
            "session_id": "MC001-DEMO-SESSION",
            "engine_mode": "SAFE",
            "cycle_number": 1,
            "mock_data": True,
        },
        "account_summary": {
            "cash_balance": 10000.0,
            "total_equity": 10250.0,
            "buying_power": 5000.0,
            "margin_used": 1000.0,
            "available_margin": 4000.0,
            "currency": "USD",
            "broker": "DEMO",
            "account_mode": "paper",
            "data_source": "MOCK",
        },
        "broker_summary": {
            "selected_broker": "DEMO",
            "broker": "DEMO",
            "broker_mode": "paper",
            "broker_type": "PAPER",
            "connected": False,
            "broker_connected": False,
            "broker_authenticated": False,
            "credential_status": "UNAVAILABLE",
            "authentication_status": "NOT_TESTED",
            "connection_status": "UNAVAILABLE",
            "account_data_health": "UNAVAILABLE",
            "market_data_status": "UNAVAILABLE",
            "balance_position_status": "UNAVAILABLE",
            "product_price_status": "UNAVAILABLE",
            "broker_health": "UNAVAILABLE",
            "execution_scope": "READ_ONLY",
            "execution_allowed": False,
            "live_trading_blocked": True,
            "broker_execution_armed": False,
            "advisory_only": True,
            "live_micro_pilot_state": "DISARMED",
            "capital_governor": f"CANONICAL_ORDER_LIMIT_CONFIG:{DEFAULT_ORDER_LIMIT_CONFIG.live_pilot_max_total_cad}CAD",
            "supported_assets": ["STOCK", "ETF", "OPTION", "FOREX", "CRYPTO"],
            "canonical_broker_runtime_state": {
                "broker": "DEMO",
                "mode": "paper",
                "credential_status": "UNAVAILABLE",
                "authentication_status": "NOT_TESTED",
                "connection_status": "UNAVAILABLE",
                "account_status": "UNAVAILABLE",
                "balance_status": "UNAVAILABLE",
                "buying_power_status": "UNAVAILABLE",
                "margin_status": "UNAVAILABLE",
                "market_data_status": "UNAVAILABLE",
                "product_status": "UNAVAILABLE",
                "overall_status": "UNAVAILABLE",
                "failure_reason": "MOCK_DATA_ONLY",
                "status_provenance": {
                    "credentials": "UNAVAILABLE",
                    "authentication": "UNAVAILABLE",
                    "connection": "UNAVAILABLE",
                    "account": "UNAVAILABLE",
                    "balances": "UNAVAILABLE",
                    "buying_power": "UNAVAILABLE",
                    "margin": "UNAVAILABLE",
                    "market_data": "UNAVAILABLE",
                    "products": "UNAVAILABLE",
                },
                "state_hash": "MOCK_STATE_HASH",
                "execution_allowed": False,
                "live_trading_blocked": True,
                "broker_execution_armed": False,
            },
        },
        "market": {
            "market_regime": "RISK_ON",
            "trend_state": "UPTREND",
            "volatility_state": "NORMAL",
            "liquidity_state": "HEALTHY",
            "momentum_state": "POSITIVE",
            "pressure_state": "BUY_PRESSURE",
            "probability_state": "FAVORABLE",
            "velocity_state": "RISING",
            "vwap_state": "ABOVE_VWAP",
            "spread_state": "TIGHT",
            "execution_cost_state": "ACCEPTABLE",
            "signal_confluence_state": "CONFIRMED",
            "data_source": "MOCK",
        },
        "risk": {
            "risk_state": "NORMAL",
            "gate_status": "OPEN",
            "current_drawdown": 0.35,
            "max_drawdown": 2.0,
            "total_exposure": 4362.5,
            "exposure_utilization": 42.56,
            "limit_breaches": [],
            "data_source": "MOCK",
        },
        "positions": {
            "open_positions": [],
            "closed_positions": [],
            "open_count": 0,
            "closed_count": 0,
            "data_source": "MOCK",
        },
        "pnl_summary": {
            "realized_pnl": 0.0,
            "unrealized_pnl": 27.5,
            "net_pnl": 27.5,
            "data_source": "MOCK",
        },
        "execution_summary": {
            "execution_state": "READY",
            "accepted_trades": 0,
            "rejected_trades": 0,
            "pending_trades": 0,
            "total_execution_cost": 0.0,
            "data_source": "MOCK",
        },
        "governance": {
            "governance_enabled": True,
            "session_locked": False,
            "defensive_mode_active": False,
            "unified_trade_gate": "AUTHORITATIVE_FAIL_CLOSED",
            "margin_gate": "AUTHORITATIVE_FAIL_CLOSED",
            "anti_bleed_guard": "AUTHORITATIVE_FAIL_CLOSED",
            "kill_switch": "AVAILABLE",
            "rbac": "READ_ONLY",
            "data_source": "MOCK",
        },
        "alerts": {
            "active": [],
            "count": 0,
            "data_source": "MOCK",
        },
        "certification_snapshot": {
            "certification": "UNAVAILABLE",
            "operational_state": "UNAVAILABLE",
            "release_candidate": "RC1",
            "execution_allowed": False,
            "live_trading_blocked": True,
            "broker_execution_armed": False,
            "advisory_only": True,
            "data_source": "MOCK",
        },
        "generated_at": now,
        "mock_data": True,
    }


__all__ = ["mission_control_mock_dashboard_payload"]
