"""
Operations Models for CSS Operations Control Centre

Helper functions to instantiate or extract operational details
using the canonical Enterprise Event model from backend.events.
"""

from backend.events.event_models import Event
from typing import Dict, Any, List, Optional

def create_health_check_event(
    component: str,
    status: str,  # OK, WARN, CRITICAL
    message: str,
    latency_ms: float,
    details: Optional[Dict[str, Any]] = None
) -> Event:
    """
    Helper to construct a canonical Event representing a component health check result.
    
    Responsibility: Standardize Event creation for component health checks.
    Dependencies: backend.events.event_models.Event
    Thread-safety: Pure function, safe.
    Integration: Generated by component health checkers and consumed by HealthMonitor.
    """
    event_payload = {
        "component": component,
        "status": status.upper(),
        "message": message,
        "latency_ms": latency_ms,
        "details": details or {}
    }
    
    severity = "INFO"
    if status.upper() == "WARN":
        severity = "WARNING"
    elif status.upper() == "CRITICAL":
        severity = "CRITICAL"

    return Event(
        event_type="HEALTH_CHECK_RESULT",
        severity=severity,
        category="SYSTEM",
        source=f"health_monitor.{component}",
        payload=event_payload
    )

def create_state_event(
    overall_status: str,  # HEALTHY, DEGRADED, CRITICAL
    health_score: float,  # 0.0 to 100.0
    component_states: Dict[str, str]
) -> Event:
    """
    Helper to construct a canonical Event representing a system state snapshot.
    
    Responsibility: Standardize Event creation for system state tracking.
    Dependencies: backend.events.event_models.Event
    Thread-safety: Pure function, safe.
    Integration: Created by OperationalStateManager.
    """
    event_payload = {
        "overall_status": overall_status.upper(),
        "health_score": health_score,
        "component_states": dict(component_states)
    }
    severity = "INFO"
    if overall_status.upper() == "DEGRADED":
        severity = "WARNING"
    elif overall_status.upper() == "CRITICAL":
        severity = "CRITICAL"

    return Event(
        event_type="SYSTEM_STATE_SNAPSHOT",
        severity=severity,
        category="SYSTEM",
        source="operational_state_manager",
        payload=event_payload
    )

def create_timeline_event(
    event_type: str,  # STATE_CHANGE, HEARTBEAT, ALERT, SYSTEM_ACTION
    severity: str,
    message: str,
    details: Optional[Dict[str, Any]] = None
) -> Event:
    """
    Helper to construct a canonical Event representing a timeline log entry.
    
    Responsibility: Standardize Event creation for timeline logs.
    Dependencies: backend.events.event_models.Event
    Thread-safety: Pure function, safe.
    Integration: Recorded inside OperationalTimeline.
    """
    event_payload = {
        "timeline_event_type": event_type.upper(),
        "message": message,
        "details": details or {}
    }
    return Event(
        event_type="TIMELINE_EVENT",
        severity=severity.upper(),
        category="SYSTEM",
        source="operational_timeline",
        payload=event_payload
    )
