"""Markdown renderer for ExecutiveMorningBrief."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from backend.executive_intelligence.utils import as_mapping


def render_markdown(brief: Mapping[str, Any]) -> str:
    panels = as_mapping(brief.get("panels"))
    decision = as_mapping(panels.get("executive_decision"))
    ops = as_mapping(panels.get("operational_health"))
    market = as_mapping(panels.get("market_intelligence"))
    trading = as_mapping(panels.get("trading_intelligence"))
    learning = as_mapping(panels.get("learning"))
    kpis = as_mapping(brief.get("executive_kpis"))
    actions = decision.get("executive_actions") or decision.get("recommended_actions") or []

    status = str(brief.get("overall_status", "UNAVAILABLE")).upper()
    lines = [
        "# CSS Daily Executive Brief",
        "",
        f"> **Status:** {status}  ",
        f"> **Report date:** {brief.get('report_date', 'UNAVAILABLE')}  ",
        f"> **Version:** {brief.get('report_version', brief.get('version', 'UNAVAILABLE'))}  ",
        f"> **Advisory only** — execution_allowed=false, live_trading_blocked=true, broker_execution_armed=false",
        "",
        "## Highest Priority Today",
    ]
    if isinstance(actions, list) and actions:
        for idx, action in enumerate(actions[:5], start=1):
            if isinstance(action, Mapping):
                lines.append(f"{idx}. **{action.get('type', 'Review')}** — {action.get('title', action.get('detail', ''))}")
            else:
                lines.append(f"{idx}. {action}")
    else:
        lines.append("1. Monitor — No prioritized actions available.")

    lines.extend(["", "## Executive KPIs"])
    for name, kpi in kpis.items():
        if name == "aliases" or not isinstance(kpi, Mapping):
            continue
        lines.append(
            f"- **{name}**: value={kpi.get('value')} · confidence={kpi.get('confidence')} · "
            f"freshness={kpi.get('freshness')} · validation={kpi.get('validation')}"
        )

    lines.extend(
        [
            "",
            "## Panels",
            f"- Executive Decision: {decision.get('panel_status', 'UNAVAILABLE')}",
            f"- Operational Health: {ops.get('panel_status', 'UNAVAILABLE')}",
            f"- Market Intelligence: {market.get('panel_status', 'UNAVAILABLE')} · regime={market.get('regime_current', 'UNAVAILABLE')}",
            f"- Trading Intelligence: {trading.get('panel_status', 'UNAVAILABLE')}",
            f"- Learning: {learning.get('panel_status', 'UNAVAILABLE')}",
            "",
            f"## Integrity",
            f"- report_id: `{brief.get('report_id', 'UNAVAILABLE')}`",
            f"- report_hash: `{brief.get('report_hash', 'PENDING')}`",
            f"- schema_version: `{brief.get('schema_version', 'UNAVAILABLE')}`",
            f"- archive_version: `{brief.get('archive_version', 'UNAVAILABLE')}`",
            f"- runtime_id: `{brief.get('runtime_id', 'UNAVAILABLE')}`",
            f"- supervisor_id: `{brief.get('supervisor_id', 'UNAVAILABLE')}`",
            f"- generated_at_utc: `{brief.get('generated_at_utc', 'UNAVAILABLE')}`",
            "",
            "---",
            "_Generated by CSS Executive Intelligence Engine (Phase 174). Advisory only._",
            "",
        ]
    )
    return "\n".join(lines)
