"""
Dashboard ViewModels for CSS Executive Operations Platform
"""

from typing import Dict, Any

class DashboardViewModel:
    """
    Formats telemetry and log structures for operational presentation views.
    """
    @staticmethod
    def format_event(event: Any) -> Dict[str, Any]:
        """Convert a canonical Event to formatted presentation output."""
        return {
            "id": event.event_id,
            "type": event.event_type,
            "severity": event.severity,
            "category": event.category,
            "source": event.source,
            "timestamp": event.timestamp,
            "message": event.payload.get("message", f"{event.event_type} event generated by {event.source}")
        }
